### ISSUE TITLE
Malicious Site Detection Bypass Not Working

### ISSUE THREAD

**Issue by surajsharma** [minbrowser/min#126]
I was trying to look at the following pdf by the world bank and it reported the pdf as a malicious site, upon clicking bypass, the page sort of blinks and the malicious site warning pops up again.

the pdf in question is the wdr report linked to here:
http://www.worldbank.org/en/publication/wdr2016

**Comment by PalmerAL** [comment]
The issue is that the PDF viewer is a local file, and ```new URL().hostname``` is an empty string for local files.

**Comment by PalmerAL** [comment]
Also, the bug that caused the warning is fixed in 0b07e536a8da249568d7c62858230152c245542c.

**Comment by surajsharma** [comment]
so how shall i proceed? given that i am still unable to view this file.

**Comment by PalmerAL** [comment]
I'm not sure what a good way to fix this is–I'll try to think about it over the next few days.

With this specific page, I'll post a 1.2.1 release in the next few hours that fixes the issue.

**Comment by surajsharma** [comment]
this is getting to be an annoying bug. cannot target specific instances, a permanent solution that addresses root cause is needed, hope this is a priority @PalmerAL

**Comment by antfu** [comment]
Just check out and didn't see the warning. I suppose this is fixed in the latest version. Closing for now
