### ISSUE TITLE
can not log in to Jetbrains Toolbox app

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1584]
- **Min Version:** 1.19.2
- **Operating system:** Arch

## Expected Behavior
when I press Approve in Min, it should switch to Toolbox app and log me in

## Actual Behavior
link changes to jetbrains://toolbox/jba/auth?code=A-ziXWz-Z7nZAsaK.... but nothing happens 

## To Reproduce
for this ofcourse Toolbox is required. install it and open then press log in and when the website opens in Min press Approve, but nothing will happen

**Comment by shalva97** [comment]
also doesnot work with obsidian links inside todoist.com

for example obsidian://open?vault=general&file=ideas%2Fwindows%20programs

**Comment by PalmerAL** [comment]
I've fixed the Jetbrains case in 2db92f46aa713747bb89b4502d2d4aacaf7aa438. It'd be great if you could retest Todoist at some point with that change and see if it also fixes that, but no worries if you can't.

**Comment by shalva97** [comment]
nope. Jetbrains case still doesnot work, but it shows pop up "open in jetbrains.desktop" but pressing OK does nothing

Todoist also doesnot work, it opens obsidian://open?... links into google search

**Comment by PalmerAL** [comment]
If the popup shows but doesn't work, then the call to openExternal() isn't working, which probably has something to do with how Arch handles opening links in default apps. I don't know much about that - do you know if there's any kind of configuration you have to do in the OS to make that work?

The second issue sounds like a Min issue; I'll look into that.

**Comment by PalmerAL** [comment]
4230324e00fb77b3a4aa6a9327703b7cb3691a80 should fix the Todoist issue - can you test it again when you get a chance?

**Comment by shalva97** [comment]
Currently I have switched to NixOS and it feel so good.... probably never gonna go back Arch Linux. I know it would be better if this comment was about Arch, but I m not going to switch to it anytime soon... and it should still be same for Arch.
Toolbox and obsidian are both now broken and I cannot fix them to test this properly, but comparing to Chromium I would say that fix is still not working.

clicking obsidian links in Min just opens new tab and nothing happens, but in Chromium it asks me to use xdg-open
![image](https://user-images.githubusercontent.com/22417494/118830413-f7cbc600-b8cf-11eb-8a64-11fc4fb58287.png)
pressing **open** fails:
![image](https://user-images.githubusercontent.com/22417494/118830478-087c3c00-b8d0-11eb-8181-6d2cab088006.png)

so I guess Min should also use xdg-open and it should show similar error as in Chromium because Obsidian is not installed properly.

**Comment by PalmerAL** [comment]
Min checks if there's an app available to open the link before showing a dialog ([code](https://github.com/minbrowser/min/blob/master/main/viewManager.js#L76-L77)), so I think this is probably intended behavior (and I expect that once you fix the xdg-open issue, it will probably work).

It might be a bit better to have an error message though.
