### ISSUE TITLE
Finding or Searching a text gives error.

### ISSUE THREAD

**Issue by Yasir-Khan22** [minbrowser/min#2368]
- **Min Version:**
Min v1.30.0
Chromium v118.0.5998.144

- **Operating system:**
 Linux Mint 21.3 Cinnamon
 Kernel: 5.15.0-91-generic

If we find or search a text within a document or web page, and if we then press backspace then it cleared all query/text except the first character. See Below :point_down: 
## Expected Behavior
![Screenshot from 2024-01-16 00-36-40](https://github.com/minbrowser/min/assets/63096083/15cfbe0e-6f85-4de3-bb51-27ed4d300514)

## Actual Behavior
![issue](https://github.com/minbrowser/min/assets/63096083/016ad506-1d71-45fb-b7cd-931833e13b1c)

**Comment by PalmerAL** [comment]
Fixed in 0ea601ae53ec79b55947ada7ed10cebbb94ac189; thanks for reporting.

**Comment by Yasir-Khan22** [comment]
@PalmerAL 
The issue is not fixed yet. I am facing it again on my same device.
The "search" method I've mentioned was "Ctrl+f".
If y're willing, I'll provide more detail about this. Now, I've to create a seperate issue for this.?

**Comment by PalmerAL** [comment]
OK, can you provide a screen recording of what happens in 1.31.1?

**Comment by Yasir-Khan22** [comment]
:point_right:  Step for reproducing the bug.

open min browser > Ctrl+F > :point_down: 

https://github.com/minbrowser/min/assets/63096083/fc114606-6fdd-49c0-96ee-ec8ab8f8d47c

**Comment by PalmerAL** [comment]
OK, thanks.

1. Can you confirm this is actually 1.31.1 (not 1.31.0)? In the top-left menu > about
2. If you type very slowly, does it still happen? In particular, if you type "c", then wait a few seconds, then delete the "c", does it work?

**Comment by MohitBansal321** [comment]
> OK, thanks.
> 
> 1. Can you confirm this is actually 1.31.1 (not 1.31.0)? In the top-left menu > about
> 2. If you type very slowly, does it still happen? In particular, if you type "c", then wait a few seconds, then delete the "c", does it work?

![image](https://github.com/minbrowser/min/assets/78220157/1332f144-4637-451a-8f04-3574636b2de5)
It still shows the first character if I do it slowly

**Comment by PalmerAL** [comment]
@MohitBansal321 You have 1.31.0 - can you try 1.31.1?

**Comment by MohitBansal321** [comment]
> @MohitBansal321 You have 1.31.0 - can you try 1.31.1?

Great its not occurring in new version

**Comment by MohitBansal321** [comment]
@Yasir-Khan22 you can also try new version

**Comment by Yasir-Khan22** [comment]
@PalmerAL 
Perfectly fine. Now we can close it as it has been completed now.
