### ISSUE TITLE
Open link in new tab, not new window.

### ISSUE THREAD

**Issue by hippylover** [minbrowser/min#390]
Hello when i open an url from a program(or from file manager i assume although i havent tested this), then min creates a whole new window with all my previous tabs and the new url... Is there some way of having min open a new url in a tab instead of creating a whole new window or could you implement this?

(also, !bookmarks doesn't work. iv'e never been able to see my bookmarks in this program but this is not so important for me as i use my own bashprogram for bookmarks)

**Comment by hippylover** [comment]
Also, it would be nice if min remembered my passwords... i made another bash program for this too but perhaps min could integrate with KDE's wallet or something. Not sure if a standard exists for this or perhaps gnome and kde have different incompatible interfaces for this.

**Comment by PalmerAL** [comment]
> Hello when i open an url from a program(or from file manager i assume although i havent tested this), then min creates a whole new window with all my previous tabs and the new url... Is there some way of having min open a new url in a tab instead of creating a whole new window or could you implement this?

Yup, I can see that happening too. I think we need to use the <a href="https://electron.atom.io/docs/api/app/#appmakesingleinstancecallback">app.makeSingleInstance()</a> API to get this to work correctly.

> (also, !bookmarks doesn't work. iv'e never been able to see my bookmarks in this program but this is not so important for me as i use my own bashprogram for bookmarks)

Not sure what's going on here, it works fine for me. Could you try this:

1. Are you putting a space after the command (so you need to type "!bookmarks " instead of just "!bookmarks"). Without the space, you're still in command-selection mode, adding the space makes the command run.
2. If you go to Developer > inspect browser > console tab, do you see any errors related to the command (they will be highlighted in red)?
3. On that same screen, if you paste this in and press enter, what number appears?
```
db.places.filter(i => i.isBookmarked).count().then(ct => console.log(ct));
```

> Also, it would be nice if min remembered my passwords... i made another bash program for this too but perhaps min could integrate with KDE's wallet or something. Not sure if a standard exists for this or perhaps gnome and kde have different incompatible interfaces for this.

I've created another issue for this here: #391.

**Comment by hippylover** [comment]
ah. ok so that's how !bookmarks work :)

Ok that works now. One additional thing that has been bothering me with 1.6 is how pressing enter only works sometimes now after iv'e selected an url. Sometimes i have to click it with my mouse(sorry didnt remember until now). This and the clicking of url in other program bug is the most annoying bugs to me.

**Comment by PalmerAL** [comment]
I've seen that too, but I haven't found a consistent way to get it to happen yet, so it's hard to figure out why it's happening. Do you have a series of steps that makes that happen consistently?

**Comment by PalmerAL** [comment]
Actually, nevermind, I think I've figured it out.

**Comment by PalmerAL** [comment]
I think that issue should be fixed in 837e63349c6e1da7a5c7995236c09b5db221e17e; could you try to build Min and see if it solves the issue for you?

**Comment by hippylover** [comment]
Can you provide a PKGBUILD for that and i will try, im not so up-to-date on npm and git and... PKGBUILD is a really simple format for building packages. Here is the one archlinux uses together with other files: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/min

**Comment by code-hunger** [comment]
@hippylover you only need to do this:

```
cd /path/to/min
npm install
grunt
electron .
```
Nothing more. Simpler than writing pkgbuild scripts. Just 3 commands.

**Comment by PalmerAL** [comment]
@code-hunger You would also need to install electron first:

```
npm install -g electron
```

**Comment by code-hunger** [comment]
Preferably from the distro package manager:
```
sudo pacman -S electron
```

**Comment by dbfreem** [comment]
Looks like this issue is fixed. If not we can reopen

**Comment by manuelmazzuola** [comment]
I still have that issue, using Archlinux and min `1.11.1`.
Clicking on links outside the browser open a new window, and that new window crashes too.

```
~ strace min
...
...
...
close(65)                               = 0
munmap(0x7f96ef372000, 131072)          = 0
epoll_ctl(28, EPOLL_CTL_DEL, 48, 0x7ffc413993a8) = -1 ENOENT (No such file or directory)
close(48)                               = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
read(29, "*", 1)                        = 1
write(30, "*", 1)                       = 1
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
read(29, "*", 1)                        = 1
rt_sigaction(SIGWINCH, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f9707bf4930}, NULL, 8) = 0
write(30, "*", 1)                       = 1
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
epoll_pwait(28, [{EPOLLIN, {u32=33, u64=33}}], 1024, 0, NULL, 8) = 1
read(33, "\1\0\0\0\0\0\0\0", 1024)      = 8
futex(0x5599dc94a4c4, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5599dc94a470, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5599dc94a4c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5599dc94a470, FUTEX_WAKE_PRIVATE, 1) = 1
epoll_pwait(28, [{EPOLLIN, {u32=33, u64=33}}], 1024, -1, NULL, 8) = 1
read(33, "\1\0\0\0\0\0\0\0", 1024)      = 8
futex(0x5599dc94a4c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5599dc94a470, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xffffeff7258ad594} ---
+++ killed by SIGSEGV (core dumped) +++
[1]    18923 segmentation fault (core dumped)  strace min
 ~  
```
